server:
  port: 8080

logging:
  level:
    root: DEBUG


pokemonapi:
  baseUrl: 'https://pokeapi.co/api/v2/pokemon'
  limit: 'limit=100'
  offset: 'offset=0'

management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: '*'
        allowed-origin-patterns: '*'
